---
core:
  secret_key: 'MTJlMjMzMDJiZGE3ODkyODg1ZDYzNmQ3ZjI3MzU5M2ZhYThlNjhhNmM0OWU4YTQy'

anymail:
  mailgun:
    api_key: 'yourmailgunkey'
    sender_domain: 'mg.example.com'
  from_email: 'cfp@example.org'

postgresql:
  user: 'gambit'
  password: 'gambit'
  port: 5432

sentry:
  dsn: 'https://x:x@sentry.io/x'
